### PR TITLE
Handle all shells’ de/activation

### LINKED ISSUE #138: Venv activation/deactivation is missing for many shell types and broken for one of the existing ones
missing:

- gitbash
- wsl
- ksh
- tcshell
- xonsh
- nushell

broken for `cshell` (tries to use `bin/activate`, instead of the cshell compatible `bin/activate.csh`)

### PR DESCRIPTION
**Pull request by flying-sheep**
Fixes #138

This adds shell activation for

- gitbash
- wsl
- ksh
- tcshell
- xonsh
- nushell

and fixes shell activation for C shell.

it also makes sure that it’s impossible to add a terminal to the enum without also adding shell activation/deactivation commands by using a `Record` type that needs to be exhaustive.

### CODE REVIEW

File: src/managers/builtin/venvUtils.ts [hunk 1]
```diff
@@ -117,44 +118,47 @@ async function getPythonInfo(env: NativeEnvInfo): Promise<PythonEnvironmentInfo>
...
         const shellActivation: Map<TerminalShellType, PythonCommandRunConfiguration[]> = new Map();
         const shellDeactivation: Map<TerminalShellType, PythonCommandRunConfiguration[]> = new Map();
 
-        // Commands for bash
-        shellActivation.set(TerminalShellType.bash, [{ executable: 'source', args: [path.join(binDir, 'activate')] }]);
-        shellDeactivation.set(TerminalShellType.bash, [{ executable: 'deactivate' }]);
-
-        // Commands for csh
-        shellActivation.set(TerminalShellType.cshell, [
-            { executable: 'source', args: [path.join(binDir, 'activate')] },
```
Comment (flying-sheep) [inline src/managers/builtin/venvUtils.ts:130]: that was broken, it’s `activate.csh`

File: src/managers/builtin/venvUtils.ts [hunk 2]
```diff
@@ -117,44 +118,47 @@ async function getPythonInfo(env: NativeEnvInfo): Promise<PythonEnvironmentInfo>
...
-        // Commands for fish
-        if (await fsapi.pathExists(path.join(binDir, 'activate.fish'))) {
-            shellActivation.set(TerminalShellType.fish, [
-                { executable: 'source', args: [path.join(binDir, 'activate.fish')] },
-            ]);
-            shellDeactivation.set(TerminalShellType.fish, [{ executable: 'deactivate' }]);
+        for (const [shell, {activate, deactivate}] of unsafeEntries(venvManagers)) {
+            if (shell === TerminalShellType.fish && activate.args && !await fsapi.pathExists(activate?.args[0])) {
+                continue;
+            }
```
Comment (flying-sheep) [inline src/managers/builtin/venvUtils.ts]: no clue why this check only existed for the fish shell and not others.

can someone help here? should this check happen for more shells?

Comment (karthiknadig) [reply src/managers/builtin/venvUtils.ts]: Older Venvs did not have `.fish`? This is to avoid using the `activate.fish` if it doesn’t exist.  May be we should add the check for all cases.

**Comment by karthiknadig** [comment]
Thanks for the PR! Love the new shell command handling.

File: src/managers/builtin/venvUtils.ts (hunk 2 above)
Comment (karthiknadig) [reply src/managers/builtin/venvUtils.ts]: Older venv example python 3.8 created using `python3.9 -m venv .venv`, does not have `.fish` or `.nu`
image

Newer venv created using `uv`:
image

Comment (flying-sheep) [reply src/managers/builtin/venvUtils.ts]: I don’t think your two examples only differ by age. I think `uv` simply uses the `virtualenv` package, which supports more shell.

So I guess the check should be in place for all shells supported by `virtualenv` and not by the builtin `venv` package.

Comment (flying-sheep) [reply src/managers/builtin/venvUtils.ts]: OK, done!

**Comment by anthonykim1** [comment]
Thanks for doing this @flying-sheep 
I mentioned https://github.com/microsoft/vscode-python-environments/issues/116, we should eventually start using shell type API. 

The list on https://github.com/microsoft/vscode/blob/e8346324cfb8b5d680ad657bb67153eb838aebc5/src/vscode-dts/vscode.proposed.terminalShellType.d.ts are subject to change, so feel free to let me know if anyone thinks more shell types could be added to make the workload easier on the extension side. As we want to make sure to cover extensive list of shell types for their specific activation.

**Review by anthonykim1 — APPROVED** [review]

**Review by karthiknadig — APPROVED** [review]
